FROM matrixdotorg/synapse:v1.100.0

ARG SYNAPSE_REPORT_STATS=no

RUN apt update; apt install sqlite3 -y
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data

COPY config_to_add.yaml /config_to_add.yaml

# for some reason synapse is having permissions problems.
# this is a workaround for now
RUN chown -R 991:991 /data
ENTRYPOINT bash -c ' \
    stat /data/homeserver.yaml || (python /start.py generate && cat /config_to_add.yaml >> /data/homeserver.yaml ); \
    chown -R 991:991 /data; \
    python /start.py'
